#! /bin/sh

basedir=$(dirname $0)
timestamp=$(date '+%Y%m%d%H%M%S')

git diff-index --cached HEAD | grep Dockerfile > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "Updating version.txt so that Dockerfile was updated."
    echo $timestamp > $basedir/../pyfontquery/version.txt
    git add $basedir/../pyfontquery/version.txt
    touch .commit
fi
