name: "Get supported releases for CentOS"
description: "Run actions to get supported releases for CentOS"
author: "tagoh"
outputs:
  releases:
    description: "Release number currently supported by CentOS"
    value: ${{ steps.centos.outputs.supported_releases }}

runs:
  using: "composite"
  steps:
    - name: Get supported releases for CentOS
      id: centos
      run: |
        (echo -n "supported_releases=["
        for i in 9 10-development; do
          echo -n "\"$i\","
        done
        echo "]") | sed -e 's/,]/]/' >> $GITHUB_OUTPUT
      shell: bash
