name: Build

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build_minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get supported releases
        id: fedora
        uses: ./.github/actions/supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          product: fedora
          release: ${{ steps.fedora.outputs.releases }}
          target: minimal
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build_extra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get supported releases
        id: fedora
        uses: ./.github/actions/supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          product: fedora
          release: ${{ steps.fedora.outputs.releases }}
          target: extra
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build_centos_minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get supported releases
        id: centos
        uses: ./.github/actions/centos_supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          product: centos
          release: ${{ steps.centos.outputs.releases }}
          target: minimal
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build_centos_extra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get supported releases
        id: centos
        uses: ./.github/actions/centos_supported_releases
      - name: Build Images
        uses: ./.github/actions/build
        with:
          product: centos
          release: ${{ steps.centos.outputs.releases }}
          target: extra
          registry_username: ${{ env.REGISTRY_USER }}
          registry_password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
